@startuml
class SpeechBubbleController {
    + SpeechBubbleController(speechBubbleListService:ISpeechBubbleListService, applicationLifetime:IHostApplicationLifetime)
    + HandleUpdatedSpeechBubble(receivedList:SpeechBubbleChainJson) : IActionResult
    + HandleRestartRequest() : IActionResult
    + {static} ParseFrontendResponseToSpeechBubbleList(receivedList:SpeechBubbleChainJson) : List<SpeechBubble>
}
ControllerBase <|-- SpeechBubbleController
SpeechBubbleController --> "speechBubbleListService" ISpeechBubbleListService
SpeechBubbleController --> "applicationLifetime" IHostApplicationLifetime
@enduml
