@startuml
class BufferTimeMonitor {
    + BufferTimeMonitor(configuration:IConfiguration, hubContext:IHubContext<CommunicationHub>, speechBubbleListService:ISpeechBubbleListService, subtitleExporterService:ISubtitleExporterService)
}
BackgroundService <|-- BufferTimeMonitor
@enduml
