@startuml
class CustomDictionaryService {
    + CustomDictionaryService()
    + ProcessCustomDictionary(customDictionary:Dictionary) : void
    + GetCustomDictionaries() : List<Dictionary>
}
ICustomDictionaryService <|-- CustomDictionaryService
@enduml
