@startuml
class ClientExchangeController {
    + ClientExchangeController(subtitleExporterService:ISubtitleExporterService, avReceiverService:IAvReceiverService)
    + <<async>> Get() : Task
}
ControllerBase <|-- ClientExchangeController
@enduml
