@startuml
class CustomDictionaryController {
    + CustomDictionaryController(dictionaryService:ICustomDictionaryService)
    + UploadCustomDictionary(transcriptionConfig:StartRecognitionMessage_TranscriptionConfig) : IActionResult
}
ControllerBase <|-- CustomDictionaryController
@enduml
