@startuml
class CommunicationHub {
    + CommunicationHub(sendingAudioService:FrontendAudioQueueService)
    + <<async>> ReceiveAudioStream(cancellationToken:CancellationToken) : IAsyncEnumerable<short[]>
}
Hub <|-- CommunicationHub
@enduml
